//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF.Website.GenresReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenreDto", Namespace="http://schemas.datacontract.org/2004/07/NF.ApplicationServices.DTOs")]
    [System.SerializableAttribute()]
    public partial class GenreDto : NF.Website.GenresReference.BaseDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenreInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenreInfo {
            get {
                return this.GenreInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreInfoField, value) != true)) {
                    this.GenreInfoField = value;
                    this.RaisePropertyChanged("GenreInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDto", Namespace="http://schemas.datacontract.org/2004/07/NF.ApplicationServices.DTOs")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NF.Website.GenresReference.GenreDto))]
    public partial class BaseDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GenresReference.IGenres")]
    public interface IGenres {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenres/GetGenres", ReplyAction="http://tempuri.org/IGenres/GetGenresResponse")]
        NF.Website.GenresReference.GenreDto[] GetGenres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenres/GetGenres", ReplyAction="http://tempuri.org/IGenres/GetGenresResponse")]
        System.Threading.Tasks.Task<NF.Website.GenresReference.GenreDto[]> GetGenresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenres/GetGenresByName", ReplyAction="http://tempuri.org/IGenres/GetGenresByNameResponse")]
        NF.Website.GenresReference.GenreDto[] GetGenresByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenres/GetGenresByName", ReplyAction="http://tempuri.org/IGenres/GetGenresByNameResponse")]
        System.Threading.Tasks.Task<NF.Website.GenresReference.GenreDto[]> GetGenresByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenres/GetGenreById", ReplyAction="http://tempuri.org/IGenres/GetGenreByIdResponse")]
        NF.Website.GenresReference.GenreDto GetGenreById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenres/GetGenreById", ReplyAction="http://tempuri.org/IGenres/GetGenreByIdResponse")]
        System.Threading.Tasks.Task<NF.Website.GenresReference.GenreDto> GetGenreByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenres/PostGenre", ReplyAction="http://tempuri.org/IGenres/PostGenreResponse")]
        string PostGenre(NF.Website.GenresReference.GenreDto genreDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenres/PostGenre", ReplyAction="http://tempuri.org/IGenres/PostGenreResponse")]
        System.Threading.Tasks.Task<string> PostGenreAsync(NF.Website.GenresReference.GenreDto genreDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenres/PutGenre", ReplyAction="http://tempuri.org/IGenres/PutGenreResponse")]
        string PutGenre(NF.Website.GenresReference.GenreDto genreDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenres/PutGenre", ReplyAction="http://tempuri.org/IGenres/PutGenreResponse")]
        System.Threading.Tasks.Task<string> PutGenreAsync(NF.Website.GenresReference.GenreDto genreDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenres/DeleteGenre", ReplyAction="http://tempuri.org/IGenres/DeleteGenreResponse")]
        string DeleteGenre(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenres/DeleteGenre", ReplyAction="http://tempuri.org/IGenres/DeleteGenreResponse")]
        System.Threading.Tasks.Task<string> DeleteGenreAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGenresChannel : NF.Website.GenresReference.IGenres, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenresClient : System.ServiceModel.ClientBase<NF.Website.GenresReference.IGenres>, NF.Website.GenresReference.IGenres {
        
        public GenresClient() {
        }
        
        public GenresClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenresClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenresClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenresClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NF.Website.GenresReference.GenreDto[] GetGenres() {
            return base.Channel.GetGenres();
        }
        
        public System.Threading.Tasks.Task<NF.Website.GenresReference.GenreDto[]> GetGenresAsync() {
            return base.Channel.GetGenresAsync();
        }
        
        public NF.Website.GenresReference.GenreDto[] GetGenresByName(string name) {
            return base.Channel.GetGenresByName(name);
        }
        
        public System.Threading.Tasks.Task<NF.Website.GenresReference.GenreDto[]> GetGenresByNameAsync(string name) {
            return base.Channel.GetGenresByNameAsync(name);
        }
        
        public NF.Website.GenresReference.GenreDto GetGenreById(int id) {
            return base.Channel.GetGenreById(id);
        }
        
        public System.Threading.Tasks.Task<NF.Website.GenresReference.GenreDto> GetGenreByIdAsync(int id) {
            return base.Channel.GetGenreByIdAsync(id);
        }
        
        public string PostGenre(NF.Website.GenresReference.GenreDto genreDto) {
            return base.Channel.PostGenre(genreDto);
        }
        
        public System.Threading.Tasks.Task<string> PostGenreAsync(NF.Website.GenresReference.GenreDto genreDto) {
            return base.Channel.PostGenreAsync(genreDto);
        }
        
        public string PutGenre(NF.Website.GenresReference.GenreDto genreDto) {
            return base.Channel.PutGenre(genreDto);
        }
        
        public System.Threading.Tasks.Task<string> PutGenreAsync(NF.Website.GenresReference.GenreDto genreDto) {
            return base.Channel.PutGenreAsync(genreDto);
        }
        
        public string DeleteGenre(int id) {
            return base.Channel.DeleteGenre(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteGenreAsync(int id) {
            return base.Channel.DeleteGenreAsync(id);
        }
    }
}
